### ISSUE TITLE
Empty list of associated products (because of CursorInterface error)

### ISSUE THREAD

**Issue by lars85** [akeneo/pim-community-dev#10349]
**I'm reporting a Bug**

If a product has related products, but no related models, the list of associated products & models will be always empty.

PHP Exception:
```
TypeError: Argument 1 passed to Pim\Bundle\DataGridBundle\Datasource\AssociatedProductModelDatasource::normalizeProductsAndProductModels() must implement interface Akeneo\Component\StorageUtils\Cursor\CursorInterface, array given, called in .../vendor/akeneo/pim-community-dev/src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php on line 115
#15 vendor/akeneo/pim-community-dev/src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php(231): normalizeProductsAndProductModels
#14 vendor/akeneo/pim-community-dev/src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php(115): getResults
#13 vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(41): getData
#12 vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Controller/GridController.php(22): getAction
#11 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): handleRaw
#10 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): handle
#9 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/SubRequestHandler.php(102): handle
#8 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php(80): render
#7 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php(87): render
#6 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php(77): render
#5 vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Datagrid/MetadataParser.php(67): getGridData
#4 vendor/akeneo/pim-community-dev/src/Pim/Bundle/DataGridBundle/Controller/DatagridController.php(48): loadAction
#3 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): handleRaw
#2 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): handle
#1 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): handle
#0 web/app.php(11): null
```

Example URL: https://host/datagrid/association-product-model-grid/load?product=12049&associationType=6&dataLocale=de_DE&params%5Bproduct%5D=12049&params%5BassociationType%5D=6&params%5BdataLocale%5D=de_DE&params%5Balias%5D=association-product-model-grid

Affected versions: all? (I've testet it in 3.1 + 2.3)

<img width="2341" alt="Lars Screen Capture 2019-07-11 at 14 29 10" src="https://user-images.githubusercontent.com/1326345/61051431-44e3d480-a3e9-11e9-93b3-ce49dd853aaa.png">

**Comment by Doodoune** [comment]
Hi @lars85,
I try to reproduce your issue. But I don't reproduce it on demo.akeneo.com.
Can you provide us a step by step scenario to reproduce this issue on demo.akeneo.com?
Regards,

**Comment by Doodoune** [comment]
Hi, 
I'm closing this issue.
Feel free to reopen it with a scenario to reproduce it.

Regards,

**Comment by lars85** [comment]
when a developer looks 5 seconds into the code he'll see the problem.

You can not reproduce the problem because demo.akeneo.com does not care about wrong types (strict types).
