### ISSUE TITLE
NO_DOCKER=true make dev

### ISSUE THREAD

**Issue by Drego058** [akeneo/pim-community-dev#12600]
I am experiencing an error when running NO_DOCKER=true make dev after installing Akeneo 4.0.

The error:

pim-community-standard]$ NO_DOCKER=true make dev
make dependencies
make[1]: Entering directory `/pim.nl/public_html/pim-community                                                                        -standard'
php -d memory_limit=4G /usr/local/bin/composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replaceme                                                                        nt was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replaceme                                                                        nt was suggested.
Package zendframework/zend-code is abandoned, you should avoid using it. Use lam                                                                        inas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it.                                                                         Use laminas/laminas-eventmanager instead.
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
62 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json
> bash vendor/akeneo/pim-community-dev/std-build/install-required-files.sh
src/ directory already exists. Not preparing the directory content.
yarnpkg install
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.97s.
make[1]: Leaving directory `/pim.nl/public_html/pim-community-                                                                        standard'
make pim-dev
make[1]: Entering directory `/pim.nl/public_html/pim-community                                                                        -standard'
make cache
make[2]: Entering directory `/pim.nl/public_html/pim-community                                                                        -standard'
rm -rf var/cache && php bin/console cache:warmup

 // Warming up the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully warmed.

make[2]: Leaving directory `/pim.nl/public_html/pim-community-standard'
make assets
make[2]: Entering directory `/pim.nl/public_html/pim-community-standard'
rm -rf public/bundles public/js
php bin/console pim:installer:assets --symlink --clean
Akeneo PIM assets
Dumping exposed routes.

[file+] /pim.nl/public_html/pim-community-standard/src/../public/js/routes.js

 Installing assets as hard copies.

 --- ------------------------------------ ----------------
      Bundle                               Method / Error
 --- ------------------------------------ ----------------
  ✔   FOSJsRoutingBundle                   copy
  ✔   OroConfigBundle                      copy
  ✔   PimUserBundle                        copy
  ✔   AkeneoPimEnrichmentBundle            copy
  ✔   AkeneoPimStructureBundle             copy
  ✔   PimAnalyticsBundle                   copy
  ✔   PimDashboardBundle                   copy
  ✔   PimDataGridBundle                    copy
  ✔   PimImportExportBundle                copy
  ✔   PimNotificationBundle                copy
  ✔   PimUIBundle                          copy
  ✔   AkeneoConnectivityConnectionBundle   copy
 --- ------------------------------------ ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.

 [OK] All assets were successfully installed.

Generating require.js main config
11:21:30 [file+] en_US.js
11:21:31 [file+] ca_ES.js
11:21:31 [file+] da_DK.js
11:21:31 [file+] de_DE.js
11:21:31 [file+] es_ES.js
11:21:31 [file+] fi_FI.js
11:21:31 [file+] fr_FR.js
11:21:31 [file+] hr_HR.js
11:21:31 [file+] it_IT.js
11:21:31 [file+] ja_JP.js
11:21:31 [file+] nl_NL.js
11:21:31 [file+] pl_PL.js
11:21:31 [file+] pt_BR.js
11:21:31 [file+] pt_PT.js
11:21:31 [file+] ru_RU.js
11:21:32 [file+] sv_SE.js
11:21:32 [file+] tl_PH.js
11:21:32 [file+] zh_CN.js
11:21:32 [file+] sv_SE.js
11:21:32 [file+] en_NZ.js

 Trying to install assets as relative symbolic links.

 --- ------------------------------------ ------------------
      Bundle                               Method / Error
 --- ------------------------------------ ------------------
  ✔   FOSJsRoutingBundle                   relative symlink
  ✔   OroConfigBundle                      relative symlink
  ✔   PimUserBundle                        relative symlink
  ✔   AkeneoPimEnrichmentBundle            relative symlink
  ✔   AkeneoPimStructureBundle             relative symlink
  ✔   PimAnalyticsBundle                   relative symlink
  ✔   PimDashboardBundle                   relative symlink
  ✔   PimDataGridBundle                    relative symlink
  ✔   PimImportExportBundle                relative symlink
  ✔   PimNotificationBundle                relative symlink
  ✔   PimUIBundle                          relative symlink
  ✔   AkeneoConnectivityConnectionBundle   relative symlink
 --- ------------------------------------ ------------------

 [OK] All assets were successfully installed.

make[2]: Leaving directory `/domains/pim.nl/public_html/pim-community-standard'
make javascript-dev
make[2]: Entering directory `/domains/pim.nl/public_html/pim-community-standard'
rm -rf public/dist
yarnpkg run webpack-dev
yarn run v1.22.4
$ yarn requirements && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js
$ node $npm_package_config_source/frontend/build/check-requirements.js
Checking PIM frontend requirements
Starting webpack from /pim.nl/public_html/pim-community-standard in dev mode
Executing pre-build scripts
(node:21573) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
$ node $npm_package_config_source/frontend/build/update-extensions.js
$ node $npm_package_config_styles
Updating form extensions.json

Starting LESS compilation

‣ vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
‣ vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/less/index.less

Version: webpack 4.29.6
Time: 2193ms
Built at: 08/20/2020 11:21:36 AM
            Asset      Size  Chunks             Chunk Names
      main.min.js  8.17 KiB    main  [emitted]  main
  main.min.js.map  6.16 KiB    main  [emitted]  main
    vendor.min.js   379 KiB  vendor  [emitted]  vendor
vendor.min.js.map   344 KiB  vendor  [emitted]  vendor
Entrypoint main = vendor.min.js vendor.min.js.map main.min.js main.min.js.map

ERROR in ./public/bundles/pimui/js/index.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No "exports" main resolved in /domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (/home/deco/domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js main[1]

ERROR in ./node_modules/core-js/modules/_array-species-create.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No "exports" main resolved in /domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ ./node_modules/core-js/modules/_array-methods.js 12:10-44
 @ ./node_modules/core-js/modules/es6.array.every.js
 @ ./node_modules/core-js/shim.js
 @ ./node_modules/babel-polyfill/lib/index.js
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js

ERROR in ./node_modules/core-js/modules/_set-species.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No "exports" main resolved in /domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (/domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ ./node_modules/core-js/modules/es7.observable.js 199:0-25
 @ ./node_modules/core-js/shim.js
 @ ./node_modules/babel-polyfill/lib/index.js
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js

ERROR in ./node_modules/core-js/modules/es6.array.species.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No "exports" main resolved in /domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (/domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ ./node_modules/core-js/shim.js 99:0-38
 @ ./node_modules/babel-polyfill/lib/index.js
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js

ERROR in (webpack)/buildin/global.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
No "exports" main resolved in domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (/domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ ./node_modules/babel-polyfill/lib/index.js 1:0-44
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js

ERROR in ./node_modules/core-js/modules/_species-constructor.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
No "exports" main resolved in/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/helper-compilation-targets/package.json
    at PoolWorker.fromErrorObj (domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /domains/pim.nl/public_html/pim-community-standard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/domains/pim.nl/public_html/pim-community-standard/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
 @ ./node_modules/core-js/modules/es7.promise.finally.js 6:25-58
 @ ./node_modules/core-js/shim.js
 @ ./node_modules/babel-polyfill/lib/index.js
 @ multi babel-polyfill ./public/bundles/pimui/js/index.js
✓ Saved CSS to public/css/pim.css
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [javascript-dev] Error 2
make[2]: Leaving directory `domains/pim.nl/public_html/pim-community-standard'
make[1]: *** [pim-dev] Error 2
make[1]: Leaving directory `/domains/pim.nl/public_html/pim-community-standard'
make: *** [dev] Error 2

**Comment by lennartbee** [comment]
If you go to vendor/akeneo/pim-community-dev/package.json and change the version number of @babel/core and @babel/preset-env to a newer version it might work. For example
`"@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",`

**Comment by freshdevelop** [comment]
I'm having the same exact problem with a fresh installation of Akeneo, taken from https://download.akeneo.com/pim-community-standard-v4.0-latest-icecat.tar.gz.

Changing @babel/core and @babel/preset-env didn't seem to fix the problem.
