### ISSUE TITLE
Product images not displayed

### ISSUE THREAD

**Issue by bartoll** [akeneo/pim-community-dev#13601]
:bug: **I'm reporting a Bug** :bug:

For version dev

    "require": {
        "akeneo/pim-community-dev": "dev-master@dev"
    },

There is a problem with displaying product images in Akeneo PIM

1. I go to the 'Edit product' window and upload a new image for any product
2. Upload finishes with no error
- file is saved in var/file_storage/catalog ...
- ajax returns new URI for this image
3. New image is not displayed after uploading
![not-displayed](https://user-images.githubusercontent.com/1619173/102908308-8bab7a00-4477-11eb-989c-cace7b1e03bb.png)
4. In IDE I can see this error
```
Symfony\Component\Routing\Exception\ResourceNotFoundException: No routes found for "/media/show/6/7/2/3/6723fda48f6004b8d1fc82a4acc57d87cb433eda_WP_20201202_15_55_00_Pro.jpg/thumbnail_small/". in /var/www/vagrant/demo1.akeneo.local/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70
Stack trace:
#0 /var/www/vagrant/demo1.akeneo.local/vendor/symfony/routing/Matcher/UrlMatcher.php(106): Symfony\Component\Routing\Matcher\CompiledUrlMatcher->match()
#1 /var/www/vagrant/demo1.akeneo.local/vendor/symfony/routing/Router.php(274): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest()
#2 /var/www/vagrant/demo1.akeneo.local/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Symfony\Component\Routing\Router->matchRequest()
#3 /var/www/vagrant/demo1.akeneo.local/vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
#4 /var/www/vagrant/demo1.akeneo.local/vendor/symfony/event-dispatcher/EventDispatcher.php
```

**Comment by bartoll** [comment]
I have found solution:

Akeneo displays product's image through URL like this
`http:/mydomain.xyz/media/show/4%252Fc%252F1%252F2%252F4c125cc21a1ddd33f9b41c68ff878935ac0626be_WP_20201202_15_54_31_Pro.jpg/thumbnail_small`
Akeneo prepares image and redirect (301) browser to URL like this
`http:/mydomain.xyz/media/cache/thumbnail_small/4/c/1/2/4c125cc21a1ddd33f9b41c68ff878935ac0626be_WP_20201202_15_54_31_Pro.jpg`

In my situation first URL was not available to Akeneo app due to Apache restrictions.
Default value for [AllowEncodedSlashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes) directive is 'Off'.
You should set it to 'NoDecode'. This settings should be added in virtual host context (setting it globally didn't work for me).

This information is missing in [official Akeneo manual](https://docs.akeneo.com/latest/install_pim/manual/installation_ce.html).

**Comment by alinolandry** [comment]
I have the same issue on akeneo 4.0 after migration from 3.2...I try the solution provide by @bartoll , but not working for me

**Comment by petrosoft-fi** [comment]
We have the same problem on Akeneo 7.0 with Firefox. Running Apache server in a new installation. Images do work on Chrome though. Request to thumbnail_small returns correct location header for redirection to the media, but the transfer fails due to NS_ERROR_UNEXPECTED. Swiching AllowEncodedSlashes value makes no difference. On Chrome images work even AllowEncodedSlashes being "Off".
