### ISSUE TITLE
Error running csv_product_export profile

### ISSUE THREAD

**Issue by dalarcia** [akeneo/pim-community-dev#14255]
:bug: **I'm reporting a Bug** :bug:

Hi when I run de csv_product_export job without filters, it rises up the following error:

-------------------------------
In ProductModel.php line 155:
                                                                               
  Return value of Akeneo\Pim\Enrichment\Component\Product\Model\ProductModel::getValuesForVariation() must be an instance of Akeneo\Pim\Enrichment\Component\Product\Model\WriteValueCollection, null returned
-------------------------------

The job finished in failed status. If I run the xlsx_csv_product_export job it works fine.
(Akeneo version: PIM CE v4.0.103)

Any idea on what could be wrong?

Thanks.

EDIT:

Hi I have put some traces (full stack trace) in the AbstractProduct.php (getAllValues method) where the error is rised, hope it helps:

#0 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php(288): Akeneo\Pim\Enrichment\Component\Product\Model\AbstractProduct->getAllValues(Object(Akeneo\Pim\Enrichment\Component\Product\Model\Product), Object(Akeneo\Pim\Enrichment\Component\Product\Model\WriteValueCollection))
#1 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Converter/MetricConverter.php(53): Akeneo\Pim\Enrichment\Component\Product\Model\AbstractProduct->getValues()
#2 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php(92): Akeneo\Pim\Enrichment\Component\Product\Converter\MetricConverter->convert(Object(Akeneo\Pim\Enrichment\Component\Product\Model\Product), Object(Akeneo\Channel\Component\Model\Channel))
#3 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/ItemStep.php(109): Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\ProductReader->read()
#4 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php(100): Akeneo\Tool\Component\Batch\Step\ItemStep->doExecute(Object(Akeneo\Tool\Component\Batch\Model\StepExecution))
#5 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(263): Akeneo\Tool\Component\Batch\Step\AbstractStep->execute(Object(Akeneo\Tool\Component\Batch\Model\StepExecution))
#6 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(226): Akeneo\Tool\Component\Batch\Job\Job->handleStep(Object(Akeneo\Tool\Component\Batch\Step\ItemStep), Object(Akeneo\Tool\Component\Batch\Model\JobExecution))
#7 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Job/Job.php(160): Akeneo\Tool\Component\Batch\Job\Job->doExecute(Object(Akeneo\Tool\Component\Batch\Model\JobExecution))
#8 /home/root_mcc/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php(216): Akeneo\Tool\Component\Batch\Job\Job->execute(Object(Akeneo\Tool\Component\Batch\Model\JobExecution))
#9 /home/root_mcc/pim/vendor/symfony/console/Command/Command.php(255): Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/root_mcc/pim/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/root_mcc/pim/vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/root_mcc/pim/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Akeneo\Tool\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/root_mcc/pim/vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/root_mcc/pim/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/root_mcc/pim/bin/console(36): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#16 {main}

**Comment by dalarcia** [comment]
Any updates on this issue?? This is blocking one of our customers exports.

**Comment by dalarcia** [comment]
Hi.

Finally we found that this error was related to an external component. Sorry for the inconvenience

Kind regards.
