### ISSUE TITLE
Bug: metric filter for measurement attribute used in product grid view.

### ISSUE THREAD

**Issue by dennishebbeler** [akeneo/pim-community-dev#16179]
Hi I had an issue all day long with my filters.

Now i have debugged it and found the following.
I think it would be cool to fix it. It might be easy with all this information.
I hope this is not caused by my version i think i have quite a new one.

Edition | CE
-- | --
5.0.61
prod
2021-12-09T17:43:35+0100
Apache/2.4.25 (Debiann)

The expected behaviour would be that a measurment filter shows up with all other active filters in the product view in the filter sidebar.

The behaviour instead is all filters are hidden. (Exception getting thrown in web console)
![akeneo_bug](https://user-images.githubusercontent.com/7593490/150435741-f477a079-4052-447d-9ded-4aed6d2bb72f.png)

>
> Uncaught TypeError: Cannot read properties of undefined (reading 'data')
>     at child.initialize (main.min.js:52134:11)
>     at child.push.IOHQ.Backbone.View (vendor.min.js:55999:21)
>     at child [as constructor] (vendor.min.js:56230:41)
>     at child [as constructor] (vendor.min.js:56230:41)
>     at child [as constructor] (vendor.min.js:56230:41)
>     at child [as constructor] (vendor.min.js:56230:41)
>     at child [as constructor] (vendor.min.js:56230:41)
>     at new child (vendor.min.js:56230:41)
>     at FiltersSelector.pYW9.FiltersSelector.getFilterModule (main.min.js:79731:49)
>     at main.min.js:79745:38
>     
>

    
I found out that the bug is in the metric-filter.js. It seems to be a buggy array search or key check with "backbone" _find function.
Don't know what that is exactly.

Exact Code there is:
```
this.emptyValue = {
        unit: _.first(_.keys(this.units)),
        type: _.findWhere(this.choices, {
          label: '='
        }).data,
        value: ''
      };
```

Error is in findWhere function. I debugged it even further having seven choices which where 5 values and the empty and not-empty choice or something. 

the _findWhere is here:

it calls _find:

```
  _.find = _.detect = function(obj, predicate, context) {
    var key;
    if (isArrayLike(obj)) {
      key = _.findIndex(obj, predicate, context);
    } else {
      key = _.findKey(obj, predicate, context);
    }
    if (key !== void 0 && key !== -1) return obj[key];
  };
```

which return undefined or didnt return anything in my case, cause the key variable ended up being -1
which was not a key in the choices array.

This predicate calls something like this:

```
  // Generator function to create the findIndex and findLastIndex functions
  function createPredicateIndexFinder(dir) {
    return function(array, predicate, context) {
      predicate = cb(predicate, context);
      var length = getLength(array);
      var index = dir > 0 ? 0 : length - 1;
      for (; index >= 0 && index < length; index += dir) {
        if (predicate(array[index], index, array)) return index;
      }
      return -1;
    };
  }
```

I would try to suggest a solution, but i have not enough knowing what it should do to work properly.
At least this should not crash all other filters, so maybe you could just build a try catch around each filter and give a proper error message in the console or even in the ui.

All this code should be here:
akeneo/node_modules/backbone/node_modules/underscore
vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js

Let me know if you need any more information about my attributes.

**Comment by dennishebbeler** [comment]
Workaround to get all filters back, would be to set Usable in grid to false if you find the attribute causing it.
