### ISSUE TITLE
Image akeneo/pim-php-dev:8.1

### ISSUE THREAD

**Issue by marcin-dorosiewicz** [akeneo/pim-community-dev#20381]
Hi,

Since 7 days we have a 100% reproducible errors when using the `akeneo/pim-php-dev:8.1` image. Executing ```docker run --rm -it akeneo/pim-php-dev:8.1 php -i``` causes a Segmentation fault (core dumped). The date coincides with the publication date of new docker image at https://hub.docker.com/layers/akeneo/pim-php-dev/8.1/images/sha256-12026ea0bfeef72a2f4f44243552f5b889b5c04bd1b609e5c5d9bd71f7287b03?context=explore.
Is it possible that the new image is broken?

backtrace extracted from the core dump:

```(gdb) bt
#0  0x00007ff37fe8c5ea in xdebug_execute_user_code_begin (execute_data=<optimized out>)
    at ./build-8.1/src/base/base.c:748
#1  0x00007ff37fe8c805 in xdebug_execute_ex (execute_data=0x7ff37fc12020)
    at ./build-8.1/src/base/base.c:880
#2  0x0000555f64c1e4bd in zend_execute ()
#3  0x00007ff37aa0e05b in bf_load_embedded_code () from /usr/lib/php/20210902/blackfire.so
#4  0x00007ff37a9f44d8 in zm_activate_blackfire () from /usr/lib/php/20210902/blackfire.so
#5  0x0000555f64bb62e0 in zend_activate_modules ()
#6  0x0000555f64b4a1fb in php_request_startup ()
#7  0x0000555f64c9491f in ?? ()
#8  0x0000555f649f3561 in ?? ()
#9  0x00007ff381ebcd0a in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000555f649f3cfa in _start ()```

**Comment by dmf-janw** [comment]
I can confirm that this error occurs. To add to that: The segmentation fault also occurs when manually building the container from the Dockerfile in this repo and using that.

In case it might be related: I'm working on an M1 Mac, but have attempted to run Akeneo on an x86_64 Linux VM via Qemu, which I had success with in the past.

**Comment by elrosi** [comment]
For me, Docker won't even run Nodejs in addition to PHP8.1.
Other containers are running.
I have removed Blackfire from docker-compose.yml.
