### ISSUE TITLE
ORM exception on pim:install --force after following a cookbook article

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5231]
**I'm reporting a Bug**

Following this tutorial: https://docs.akeneo.com/1.6/cookbook/category/add-properties-to-category.html

and then `migrations:diff`, `migrations:migrate` on existing installation.

All works well.

But I am getting the following error on `php app/console pim:install --force`

```
An error occurred during the fixtures execution.  
Error #0 in class Doctrine\ORM\ORMException: Found entity of type  
Pim\Bundle\CatalogBundle\Entity\CategoryTranslation on association  
Acme\Bundle\ExtendedCategoryBundle\Entity\Category#translations, but expecting  
Acme\Bundle\ExtendedCategoryBundle\Entity\CategoryTranslation  
```

I am using 
```
Edition	CE
Version	1.6.4
```

Here is the full stacktrace:

```
Creating database schema...
Database schema created successfully!
Nothing to update - your database is already in sync with the current entity metadata.
Create session table
Load jobs for fixtures. (data set: PimInstallerBundle:minimal)
Fixtures fixtures_currency_csv has been successfully executed.
Fixtures fixtures_locale_csv has been successfully executed.
Fixtures fixtures_user_group_csv has been successfully executed.
Fixtures fixtures_group_type_csv has been successfully executed.
Fixtures fixtures_attribute_group_csv has been successfully executed.
An error occurred during the fixtures execution.
Error #0 in class Doctrine\ORM\ORMException: Found entity of type Pim\Bundle\CatalogBundle\Entity\CategoryTranslation on association Acme\Bundle\ExtendedCategoryBundle\Entity\Category#translations, but expecting Acme\Bundle\ExtendedCategoryBundle\Entity\CategoryTranslation
#0 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(687): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Doctrine\ORM\PersistentCollection))
#1 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(404): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Acme\Bundle\ExtendedCategoryBundle\Entity\Category))
#2 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(711): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#3 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(297): Doctrine\ORM\UnitOfWork->computeChangeSets()
#4 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(340): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php(85): Doctrine\ORM\EntityManager->flush()
#6 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Component/Connector/Writer/Database/Writer.php(47): Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver->saveAll(Array)
#7 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(190): Pim\Component\Connector\Writer\Database\Writer->write(Array)
#8 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php(125): Akeneo\Component\Batch\Step\ItemStep->write(Array)
#9 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/AbstractStep.php(100): Akeneo\Component\Batch\Step\ItemStep->doExecute(Object(Akeneo\Component\Batch\Model\StepExecution))
#10 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(264): Akeneo\Component\Batch\Step\AbstractStep->execute(Object(Akeneo\Component\Batch\Model\StepExecution))
#11 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(227): Akeneo\Component\Batch\Job\Job->handleStep(Object(Akeneo\Component\Batch\Step\ItemStep), Object(Akeneo\Component\Batch\Model\JobExecution))
#12 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php(161): Akeneo\Component\Batch\Job\Job->doExecute(Object(Akeneo\Component\Batch\Model\JobExecution))
#13 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php(161): Akeneo\Component\Batch\Job\Job->execute(Object(Akeneo\Component\Batch\Model\JobExecution))
#14 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(259): Akeneo\Bundle\BatchBundle\Command\BatchCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Akeneo\Bundle\BatchBundle\Command\BatchCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(164): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('akeneo:batch:jo...', Array)
#21 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php(108): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->loadFixturesStep(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(259): Pim\Bundle\InstallerBundle\Command\DatabaseCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\DatabaseCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php(60): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(121): Pim\Bundle\InstallerBundle\CommandExecutor->runCommand('pim:installer:d...')
#29 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php(77): Pim\Bundle\InstallerBundle\Command\InstallCommand->databaseStep(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(259): Pim\Bundle\InstallerBundle\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Pim\Bundle\InstallerBundle\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/app/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#36 {main}
The command terminated with an error code: 1.


                                                 
  [Exception]                                    
  The command terminated with an error code: 1.  
                                                 


Exception trace:
 () at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php:66
 Pim\Bundle\InstallerBundle\CommandExecutor->runCommand() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php:164
 Pim\Bundle\InstallerBundle\Command\DatabaseCommand->loadFixturesStep() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php:108
 Pim\Bundle\InstallerBundle\Command\DatabaseCommand->execute() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/CommandExecutor.php:60
 Pim\Bundle\InstallerBundle\CommandExecutor->runCommand() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php:121
 Pim\Bundle\InstallerBundle\Command\InstallCommand->databaseStep() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/akeneo/pim-community-dev/src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php:77
 Pim\Bundle\InstallerBundle\Command\InstallCommand->execute() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/akeneo-v2/akeneo-staging/app/console:29
```

**Comment by fabienlem** [comment]
Hello @wakqasahmed!

I think you have an issue in you mapping overriding. Can you ensure everything is fine in the **app/config/config.yml** config file? (inside **mapping_overrides** parameter).

Regards,
Fabien

**Comment by wakqasahmed** [comment]
@fabienlem 

Try it with 1.6? Quite possible, you will run into the same issue. As i have tried it with multiple builds.

**Comment by fabienlem** [comment]
Hello @wakqasahmed,

Ok, I will take a look on this soon. I will keep you updated.

Regards,
Fabien

**Comment by fabienlem** [comment]
Hello @wakqasahmed,

I checked with Damien, I confirm you the documentation improvement will be released soon.

I'm closing this issue, feel free to reopen it if necessary.

Regards,
Fabien

**Comment by wakqasahmed** [comment]
Well, is it merely documentation issue or require some fix as well?

**Comment by wakqasahmed** [comment]
@fabienlem Related to the above issue

> I am ready to contribute, if assigned

I found that `Pim\Component\Catalog\Model\AbstractAttribute` (https://github.com/akeneo/pim-community-dev/blob/v1.6.5/src/Pim/Component/Catalog/Model/AbstractAttribute.php) is producing an error:

```
Fatal error: Call to undefined method Pim\Bundle\CatalogBundle\Entity\AttributeTranslation::setDefinition() in /akeneo-staging/src/Acme/Bundle/ExtendedAttributeBundle/Entity/Attribute.php on line 83
[2016-12-08 11:34:33] php.CRITICAL: Fatal Error: Call to undefined method Pim\Bundle\CatalogBundle\Entity\AttributeTranslation::setDefinition() {"type":1,"file":"/akeneo-staging/src/Acme/Bundle/ExtendedAttributeBundle/Entity/Attribute.php","line":83,"level":6135,"stack":[]} 


                                                                                                                                
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                  
  Attempted to call an undefined method named "setDefinition" of class "Pim\Bundle\CatalogBundle\Entity\AttributeTranslation".  
                                                                                                                                


akeneo:batch:job [-c|--config CONFIG] [--email EMAIL] [--no-log] [--] <code> [<execution>]
```

It is due to the hardcoded dependency nature of the following function in the `AbstractAttribute` class:

```
    /**
     * {@inheritdoc}
     */
    public function getTranslationFQCN()
    {
        return 'Pim\Bundle\CatalogBundle\Entity\AttributeTranslation';
    }
```

BTW: overriding this function in my overridden Attribute Entity solves the issue but i think it should be fixed and `AttributeTranslation` entity should be passed as `$translationDataClass` via dependency injection.

**Comment by wakqasahmed** [comment]
@fabienlem Same is the case with Category, the following error:

It is due to the hardcoded dependency nature of the following function in the `Category` (`Pim\Bundle\CatalogBundle\Entity\Category.php`) class:

```
CATEGORY IMPORT IN CSV  Found entity of type Pim\Bundle\CatalogBundle\Entity\CategoryTranslation on association Acme\Bundle\ExtendedAttributeBundle\Entity\Category#translations, but expecting Acme\Bundle\ExtendedAttributeBundle\Entity\CategoryTranslation
```

```
    /**
     * {@inheritdoc}
     */
    public function getTranslationFQCN()
    {
        return 'Pim\Bundle\CatalogBundle\Entity\CategoryTranslation';
    }

```

**Comment by wakqasahmed** [comment]
@fabienlem Please re-open this issue

**Comment by XzAeRo** [comment]
If anyone is struggling with this problem, you should do the following.

In your `src/Application/PimCatalogBundle/Entity/AttributeGroup.php` file, you should have something like this:

```php
<?php
namespace Application\PimCatalogBundle\Entity;

[...]
use Pim\Bundle\CatalogBundle\Model\AttributeGroupInterface;
[...]

class AttributeGroup implements AttributeGroupInterface {
    [...]

    /**
     * {@inheritdoc}
     */
    public function getTranslationFQCN()
    {
        return 'Pim\Bundle\CatalogBundle\Entity\AttributeGroupTranslation';
    }

    [...]
}
```

Just change `return 'Pim\Bundle\CatalogBundle\Entity\AttributeGroupTranslation';` for `return 'Application\PimCatalogBundle\Entity\AttributeGroupTranslation';`. The same procedure applies to `CategoryGroup`, as @wakqasahmed stated before.

**Comment by wakqasahmed** [comment]
@XzAeRo I think i didn't understand your solution fully. Are you suggesting to change the code in the core files?

**Comment by XzAeRo** [comment]
@wakqasahmed no, it's just a suggestion to anyone who comes around this problem

**Comment by jmleroux** [comment]
Hello,

This version is not supported anymore. Feel free to reopen this issue if needed.

Regards
