### ISSUE TITLE
JS: Channels and associations json problem

### ISSUE THREAD

**Issue by ekussberg** [akeneo/pim-community-dev#6066]
Version:   1.7.2
OS:           Mac OS (latest)
Browser:  Chrome, Safari

When i open channels or associations, i get a JSON problem:
```
/enrich/product/?dataLocale=de_DE#url=/configuration/channel/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.eval [as success] (eval at <anonymous> (jquery-1.10.2.js:612), <anonymous>:130:100)
    at fire (jquery-1.10.2.js:3048)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.js:3160)
    at done (jquery-1.10.2.js:8235)
    at XMLHttpRequest.callback (jquery-1.10.2.js:8778)
```
and here is the prod.log:
```
[2017-04-13 22:38:30] request.INFO: Matched route "pim_datagrid_load". {"route_parameters":{"_controller":"pim_datagrid.controller.datagrid:loadAction","alias":"attribute-grid","_route":"pim_datagrid_load"},"request_uri":"http://pim.lead-energy.com/datagrid/attribute-grid/load?attribute-grid%5B_parameters%5D%5Bview%5D%5Bcolumns%5D=code%2Clabel%2Ctype%2Cscopable%2Clocalizable%2Cgroup&localeCode=de_DE&params%5BlocaleCode%5D=de_DE"} []
[2017-04-13 22:38:30] request.INFO: Matched route "oro_datagrid_index". {"route_parameters":{"_controller":"Oro\\Bundle\\DataGridBundle\\Controller\\GridController::getAction","gridName":"attribute-grid","_route":"oro_datagrid_index"},"request_uri":"http://pim.lead-energy.com/datagrid/attribute-grid?attribute-grid%5B_parameters%5D%5Bview%5D%5Bcolumns%5D=code%2Clabel%2Ctype%2Cscopable%2Clocalizable%2Cgroup&attribute-grid%5BlocaleCode%5D=de_DE"} []
[2017-04-13 22:38:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'SELECT COUNT(*) FROM (SELECT p0_.id AS id0, p0_.sort_order AS sort_order1, p0_.useable_as_grid_filter AS useable_as_grid_filter2, p0_.max_characters AS max_characters3, p0_.validation_rule AS validation_rule4, p0_.validation_regexp AS validation_regexp5, p0_.wysiwyg_enabled AS wysiwyg_enabled6, p0_.number_min AS number_min7, p0_.number_max AS number_max8, p0_.decimals_allowed AS decimals_allowed9, p0_.negative_allowed AS negative_allowed10, p0_.date_min AS date_min11, p0_.date_max AS date_max12, p0_.metric_family AS metric_family13, p0_.default_metric_unit AS default_metric_unit14, p0_.max_file_size AS max_file_size15, p0_.allowed_extensions AS allowed_extensions16, p0_.minimumInputLength AS minimumInputLength17, p0_.is_required AS is_required18, p0_.is_unique AS is_unique19, p0_.is_localizable AS is_localizable20, p0_.is_scopable AS is_scopable21, p0_.code AS code22, p0_.entity_type AS entity_type23, p0_.attribute_type AS attribute_type24, p0_.backend_type AS backend_type25, p0_.properties AS properties26, p0_.created AS created27, p0_.updated AS updated28, p0_.id AS id29, p0_.sort_order AS sort_order30, p0_.useable_as_grid_filter AS useable_as_grid_filter31, p0_.max_characters AS max_characters32, p0_.validation_rule AS validation_rule33, p0_.validation_regexp AS validation_regexp34, p0_.wysiwyg_enabled AS wysiwyg_enabled35, p0_.number_min AS number_min36, p0_.number_max AS number_max37, p0_.decimals_allowed AS decimals_allowed38, p0_.negative_allowed AS negative_allowed39, p0_.date_min AS date_min40, p0_.date_max AS date_max41, p0_.metric_family AS metric_family42, p0_.default_metric_unit AS default_metric_unit43, p0_.max_file_size AS max_file_size44, p0_.allowed_extensions AS allowed_extensions45, p0_.minimumInputLength AS minimumInputLength46, p0_.is_required AS is_required47, p0_.is_unique AS is_unique48, p0_.is_localizable AS is_localizable49, p0_.is_scopable AS is_scopable50, p0_.code AS code51, p0_.entity_type AS entity_type52, p0_.attribute_type AS attribute_type53, p0_.backend_type AS backend_type54, p0_.properties AS properties55, p0_.created AS created56, p0_.updated AS updated57, (CASE WHEN p1_.label IS NULL THEN p0_.code ELSE p1_.label END) AS sclr58, (CASE WHEN p2_.label IS NULL THEN p3_.code ELSE p2_.label END) AS sclr59, p1_.label AS label60, p3_.code AS code61, p0_.group_id AS group_id62 FROM pim_catalog_attribute p0_ LEFT JOIN pim_catalog_attribute_translation p1_ ON p0_.id = p1_.foreign_key AND (p1_.locale = ?) LEFT JOIN pim_catalog_attribute_group p3_ ON p0_.group_id = p3_.id LEFT JOIN pim_catalog_attribute_group_translation p2_ ON p3_.id = p2_.foreign_key AND (p2_.locale = ?) GROUP BY p0_.id) AS e' with params ["de_DE", "de_DE"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #59 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'akeneo_pim.p1_.label' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/pim.lead-energy.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'SELECT COUNT(*) FROM (SELECT p0_.id AS id0, p0_.sort_order AS sort_order1, p0_.useable_as_grid_filter AS useable_as_grid_filter2, p0_.max_characters AS max_characters3, p0_.validation_rule AS validation_rule4, p0_.validation_regexp AS validation_regexp5, p0_.wysiwyg_enabled AS wysiwyg_enabled6, p0_.number_min AS number_min7, p0_.number_max AS number_max8, p0_.decimals_allowed AS decimals_allowed9, p0_.negative_allowed AS negative_allowed10, p0_.date_min AS date_min11, p0_.date_max AS date_max12, p0_.metric_family AS metric_family13, p0_.default_metric_unit AS default_metric_unit14, p0_.max_file_size AS max_file_size15, p0_.allowed_extensions AS allowed_extensions16, p0_.minimumInputLength AS minimumInputLength17, p0_.is_required AS is_required18, p0_.is_unique AS is_unique19, p0_.is_localizable AS is_localizable20, p0_.is_scopable AS is_scopable21, p0_.code AS code22, p0_.entity_type AS entity_type23, p0_.attribute_type AS attribute_type24, p0_.backend_type AS backend_type25, p0_.properties AS properties26, p0_.created AS created27, p0_.updated AS updated28, p0_.id AS id29, p0_.sort_order AS sort_order30, p0_.useable_as_grid_filter AS useable_as_grid_filter31, p0_.max_characters AS max_characters32, p0_.validation_rule AS validation_rule33, p0_.validation_regexp AS validation_regexp34, p0_.wysiwyg_enabled AS wysiwyg_enabled35, p0_.number_min AS number_min36, p0_.number_max AS number_max37, p0_.decimals_allowed AS decimals_allowed38, p0_.negative_allowed AS negative_allowed39, p0_.date_min AS date_min40, p0_.date_max AS date_max41, p0_.metric_family AS metric_family42, p0_.default_metric_unit AS default_metric_unit43, p0_.max_file_size AS max_file_size44, p0_.allowed_extensions AS allowed_extensions45, p0_.minimumInputLength AS minimumInputLength46, p0_.is_required AS is_required47, p0_.is_unique AS is_unique48, p0_.is_localizable AS is_localizable49, p0_.is_scopable AS is_scopable50, p0_.code AS code51, p0_.entity_type AS entity_type52, p0_.attribute_type AS attribute_type53, p0_.backend_type AS backend_type54, p0_.properties AS properties55, p0_.created AS created56, p0_.updated AS updated57, (CASE WHEN p1_.label IS NULL THEN p0_.code ELSE p1_.label END) AS sclr58, (CASE WHEN p2_.label IS NULL THEN p3_.code ELSE p2_.label END) AS sclr59, p1_.label AS label60, p3_.code AS code61, p0_.group_id AS group_id62 FROM pim_catalog_attribute p0_ LEFT JOIN pim_catalog_attribute_translation p1_ ON p0_.id = p1_.foreign_key AND (p1_.locale = ?) LEFT JOIN pim_catalog_attribute_group p3_ ON p0_.group_id = p3_.id LEFT JOIN pim_catalog_attribute_group_translation p2_ ON p3_.id = p2_.foreign_key AND (p2_.locale = ?) GROUP BY p0_.id) AS e' with params [\"de_DE\", \"de_DE\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #59 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'akeneo_pim.p1_.label' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/pim.lead-energy.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #59 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'akeneo_pim.p1_.label' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/pim.lead-energy.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:694)"} []
```
solution i found is to go to MySQL and disable only_full_group_by:
```
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```

**Comment by ekussberg** [comment]
Second error i get now:
```
form.js:231 Uncaught Error: Zone "buttons" does not exist
    at child.getZone (http://pim.lead-energy.com/bundles/pimenrich/js/product/form.js:231:27)
    at child.renderExtension (http://pim.lead-energy.com/bundles/pimenrich/js/product/form.js:202:22)
    at child.<anonymous> (http://pim.lead-energy.com/bundles/pimenrich/js/product/form.js:190:26)
    at Function._.each._.forEach (http://pim.lead-energy.com/bundles/pimui/lib/underscore/underscore.js:158:9)
    at child.renderExtensions (http://pim.lead-energy.com/bundles/pimenrich/js/product/form.js:189:19)
    at child.<anonymous> (http://pim.lead-energy.com/bundles/pimenrich/js/grid/view-selector.js:118:26)
    at Object.<anonymous> (http://pim.lead-energy.com/bundles/pimui/lib/jquery/jquery-1.10.2.js:3204:33)
    at fire (http://pim.lead-energy.com/bundles/pimui/lib/jquery/jquery-1.10.2.js:3048:30)
    at Object.fireWith [as resolveWith] (http://pim.lead-energy.com/bundles/pimui/lib/jquery/jquery-1.10.2.js:3160:7)
    at Object.deferred.(anonymous function) [as resolve] (http://pim.lead-energy.com/bundles/pimui/lib/jquery/jquery-1.10.2.js:3249:34)
```

**Comment by jmleroux** [comment]
hello @ekussberg ,

> solution i found is to go to MySQL and disable only_full_group_by:

this is a known and documented limitation: https://docs.akeneo.com/1.7/reference/technical_information/server_side_setup_for_hosting.html#software

![image](https://cloud.githubusercontent.com/assets/1516770/25027478/37956b20-20ad-11e7-8a30-6d76fa5b6ee9.png)

:wink:

**Comment by jmleroux** [comment]
Your second error is weird, the dropzone is wel found in the channels screen source code.

http://demo.akeneo.com/#url=/configuration/channel/

![image](https://cloud.githubusercontent.com/assets/1516770/25038141/614a4602-20fd-11e7-93e5-91b69e5b353f.png)

Did you make any customization?

**Comment by ekussberg** [comment]
@jmleroux should be something with cache, when i cleaned it up and reinstalled now works great 🔥

**Comment by DavidFeller** [comment]
@jmleroux I'm struggling with exactly the same error message @ekussberg mentioned as his second problem. When I create a new product all dropzone fields are missing until I add them manually and immediately upload an image. Otherwise they disappear on saving.

It's a "fresh" installation and I cleared all caches. Any Ideas?

![akeneo_20170430](https://cloud.githubusercontent.com/assets/2094727/25562404/a46dadd6-2d85-11e7-93c1-96e3d93e8a8e.png)

**Comment by nei** [comment]
I am getting the error on the product edit page PIM 1.7 EE.

It is trying to execute js from the product grid on the product edit form, it seems it is trying to load the create view button there but the zone is not yet available. Debugging the js I can see the area buttons is being created normally for the next interations.

So, I am assuming it is loading js in the wrong place.

```Error: Zone "buttons" does not exist at child.getZone (https://project.com/bundles/pimenrich/js/product/form.js:231:27) at child.renderExtension```

**Comment by LaureBro** [comment]
Hi @DavidFeller, can we follow up this issue in @nei latest issue #6280 ?
Can you tell us in #6280 what is your exact PIM version (for instance 1.7.5).
Thanks!
