### ISSUE TITLE
Exception after updating 2.0.0 to 2.0.1 or 2.0.2

### ISSUE THREAD

**Issue by crapougnax** [akeneo/pim-community-dev#7014]
From a fresh `2.0.0` install, any attempt to change the version of the `akeneo/pim-community-dev` package version to `2.0.1` or `2.0.2` in `composer.json` ends up with 

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "LoadProductTemplateValuesSubscriber" from namespace "Pim\Bundle\CatalogBundle\EventSubscriber".
Did you forget a "use" statement for another namespace? in /home/quatrain/pim-2.0/pim-community-standard/var/cache/prod/appProdProjectContainer.php:8699
Stack trace:
#0 /home/quatrain/pim-2.0/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(335): appProdProjectContainer->getPimCatalog_EventSubscriber_LoadProductTemplateValuesService()
#1 /home/quatrain/pim-2.0/pim-community-standard/var/cache/prod/appProdProjectContainer.php(3162): Symfony\Component\DependencyInjection\Container->get('pim_catalog.eve...')
#2 /home/quatrain/pim-2.0/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(335): appProdProjectContainer->getDoctrine_Dbal_DefaultConnectionService()
#3 /home/quatrain/pim-2.0/pim-community-standard/var/cache/prod/appPr in /home/quatrain/pim-2.0/pim-community-standard/var/cache/prod/appProdProjectContainer.php on line 8699
```

So sad.

**Comment by nidup** [comment]
Hi @crapougnax 

You can drop your symfony cache + restart fpm :wink:

**Comment by crapougnax** [comment]
Yup, though, it needed a violent `rm -fr var/cache/*` ('cause the `bin/console cache:clear --no-warmup --env=prod`produced an exception)  then a `service php7.1-fpm restart` did the trick.

Many thanks.

**Comment by crapougnax** [comment]
... and a `yarn run webpack`is quite welcome too :-)
