### ISSUE TITLE
yarn run webpack, permission denied

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#7105]
Hello,
With Akeneo CE 2.0.0 i've this problem 

```
root@fd5447edca6a:/var/www/html/pim-community-standard# yarn --verbose run webpack
yarn run v1.2.1
warning package.json: No license field
verbose 0.345 Checking for configuration file "/var/www/html/pim-community-standard/.npmrc".
verbose 0.345 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.345 Checking for configuration file "/usr/etc/npmrc".
verbose 0.345 Checking for configuration file "/root/.npmrc".
verbose 0.346 Checking for configuration file "/var/www/html/pim-community-standard/.npmrc".
verbose 0.346 Checking for configuration file "/var/www/html/.npmrc".
verbose 0.346 Checking for configuration file "/var/www/.npmrc".
verbose 0.346 Checking for configuration file "/var/.npmrc".
verbose 0.347 Checking for configuration file "/var/www/html/pim-community-standard/.yarnrc".
verbose 0.347 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.347 Found configuration file "/usr/local/share/.yarnrc".
verbose 0.347 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.347 Checking for configuration file "/root/.yarnrc".
verbose 0.348 Checking for configuration file "/var/www/html/pim-community-standard/.yarnrc".
verbose 0.348 Checking for configuration file "/var/www/html/.yarnrc".
verbose 0.348 Checking for configuration file "/var/www/.yarnrc".
verbose 0.348 Checking for configuration file "/var/.yarnrc".
verbose 0.351 current time: 2017-11-03T09:07:03.706Z
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
/bin/sh: 1: webpack: Permission denied
verbose 0.979 Error: Command failed with exit code 126.
    at /usr/share/yarn/lib/cli.js:35603:15
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm testing with the 2.0.5 patch and it's identical

yarn -v : 1.2.1
Debian strech
nodejs v8.9.0

**Comment by tamarasaurus** [comment]
Hi @Philippe-M 

Could you try with node 8.2.1 and yarn 1.0.0 and let us know if you have any issues? Did you have any issue running `yarn install` ? 

Thank you

**Comment by tamarasaurus** [comment]
Hey @Philippe-M any update about this issue? Did you get it working?

Regards,
Tamara

**Comment by ankit-sf** [comment]
Getting same issue with 
 node: v6.13.1 
 yarn: 1.3.2
 php: 7.1.5
Akeneo 2.1.7 (community)

`$ yarn run webpack`
`yarn run v1.3.2
warning package.json: No license field
$ /opt/bitnami/nodejs/bin/yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules /opt/bitnami/nodejs/bin/node $npm_package_config_check --source=$npm_package_config_source
/bin/sh: 1: webpack: Permission denied
error Command failed with exit code 126.`

**Comment by ankit-sf** [comment]
fyi: Resolved issue by installing webpack. webpack was not install

**Comment by Philippe-M** [comment]
Hello, i'm create a new test with akeneo 2.3.11 to update 2.3.12 and after use this command

```
service php7.1-fpm restart
rm -rf var/cache/* ./web/bundles/* ./web/css/* ./web/js/*
bin/console --env=prod pim:installer:assets
bin/console --env=prod cache:warmup
```

i've this error 

```
yarn --verbose run webpack
yarn run v1.10.1
warning package.json: No license field
verbose 0.232 Checking for configuration file "/var/www/html/pim-project/.npmrc".
verbose 0.233 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.233 Checking for configuration file "/usr/etc/npmrc".
verbose 0.233 Checking for configuration file "/root/.npmrc".
verbose 0.233 Checking for configuration file "/var/www/html/pim-project/.npmrc".
verbose 0.233 Checking for configuration file "/var/www/html/.npmrc".
verbose 0.234 Checking for configuration file "/var/www/.npmrc".
verbose 0.234 Checking for configuration file "/var/.npmrc".
verbose 0.235 Checking for configuration file "/var/www/html/pim-project/.yarnrc".
verbose 0.235 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.235 Found configuration file "/usr/local/share/.yarnrc".
verbose 0.235 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.235 Checking for configuration file "/root/.yarnrc".
verbose 0.236 Checking for configuration file "/var/www/html/pim-project/.yarnrc".
verbose 0.236 Checking for configuration file "/var/www/html/.yarnrc".
verbose 0.236 Checking for configuration file "/var/www/.yarnrc".
verbose 0.236 Checking for configuration file "/var/.yarnrc".
verbose 0.24 current time: 2018-10-17T13:05:37.698Z
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source

You have some npm dependencies that are out of date with the PIM:

    Updated
    - webpack@^4.20.2 -> 3.5.5


Automatically syncing your dependencies...

  Running: yarn add webpack@3.5.5 

warning package.json: No license field
warning pim-community-standard@2.0.0: No license field
warning pim-community-standard@2.0.0: No license field
/bin/sh: 1: webpack: Permission denied
verbose 18.88 Error: Command failed with exit code 126.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:243:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:272:123)
    at /usr/share/yarn/lib/cli.js:34808:15
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:98:30)
    at /usr/share/yarn/lib/cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wa-daniel-fahl** [comment]
@Philippe-M did you try running `yarn install` previously?
That appears to have fixed the issue that @ankit-sf reported.

**Comment by Doodoune** [comment]
This issue is solved.
You need to install yarn & launch `yarn run webpack`.

I close this issue,
feel free to reopen it if you still have a problem.

Regards,

**Comment by syukronarie** [comment]
> Hi @Philippe-M
> 
> Could you try with node 8.2.1 and yarn 1.0.0 and let us know if you have any issues? Did you have any issue running `yarn install` ?
> 
> Thank you



> Hi @Philippe-M
> 
> Could you try with node 8.2.1 and yarn 1.0.0 and let us know if you have any issues? Did you have any issue running `yarn install` ?
> 
> Thank you

thank you for reminding... sometimes forgetfulness :DDD

**Comment by asenges** [comment]
This final solution 

$ sudo yarn install && sudo yarn run webpack

before setup and install the component worked for me!
