### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\EnrichBundle\PimEnrichBundle' not found in /app/AppKernel.php:88

### ISSUE THREAD

**Issue by passboltUser** [akeneo/pim-community-dev#7149]
Following this https://docs.akeneo.com/master/cookbook/setup_data/add_translation_packs.html I'm trying to change the language to German. 

I moved  `vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle` to `app/Resources/PimEnrichBundle`

It seems the mentioned `php app/console ..` has changed. I tried `php bin/console ..` but I'm getting this error:
```
# php bin/console oro:translation:dump de --env=prod
PHP Fatal error:  Uncaught Error: Class 'Pim\Bundle\EnrichBundle\PimEnrichBundle' not found in /var/www/html/akeneo/pim-community-standard/app/AppKernel.php:88
Stack trace:
#0 /var/www/html/akeneo/pim-community-standard/app/AppKernel.php(47): AppKernel->getPimBundles()
#1 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#2 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
#4 /var/www/html/akeneo/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#5 /var/www/html/akeneo/pim-community-standard/vendor/symfony in /var/www/html/akeneo/pim-community-standard/app/AppKernel.php on line 88
```
What's wrong?

**Comment by passboltUser** [comment]
I had to copy EnrichBundle back to its original folder or I was getting a blank page.
`cp app/Resources/PimEnrichBundle vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle -R`

**Comment by passboltUser** [comment]
Ok, I found where the language can be set, it's under `/#/system/`
