### ISSUE TITLE
JS Error: Cannot find module "pim/family-variant-edit-form/axes"

### ISSUE THREAD

**Issue by riconeitzel** [akeneo/pim-community-dev#7933]
We're using the Community Edition. After Upgrading to the latest Version we encounter the following issues:

Login Mask -> Enter Credentials -> Click Login

"Cannot find module "pim/family-variant-edit-form/axes"" <-- JS Console Error

If you run ```yarn --verbose run webpack```

the following output comes up:

```
yarn run v1.5.1
warning package.json: No license field
verbose 0.637 Checking for configuration file "/var/www/html/pim-community-standard/.npmrc".
verbose 0.637 Checking for configuration file "/home/akeneo/.npmrc".
verbose 0.638 Checking for configuration file "/usr/etc/npmrc".
verbose 0.638 Checking for configuration file "/var/www/html/pim-community-standard/.npmrc".
verbose 0.638 Checking for configuration file "/var/www/html/.npmrc".
verbose 0.639 Checking for configuration file "/var/www/.npmrc".
verbose 0.639 Checking for configuration file "/var/.npmrc".
verbose 0.641 Checking for configuration file "/var/www/html/pim-community-standard/.yarnrc".
verbose 0.641 Checking for configuration file "/home/akeneo/.yarnrc".
verbose 0.641 Found configuration file "/home/akeneo/.yarnrc".
verbose 0.642 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.642 Checking for configuration file "/var/www/html/pim-community-standard/.yarnrc".
verbose 0.643 Checking for configuration file "/var/www/html/.yarnrc".
verbose 0.643 Checking for configuration file "/var/www/.yarnrc".
verbose 0.644 Checking for configuration file "/var/.yarnrc".
verbose 0.647 current time: 2018-04-05T14:46:18.456Z
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
Starting webpack from /var/www/html/pim-community-standard in prod mode

WebpackCleanupPlugin: 0 file(s) deleted.
Version: webpack 3.5.5
Time: 11901ms
              Asset     Size  Chunks                    Chunk Names
        main.min.js  2.05 MB       0  [emitted]  [big]  main
         lib.min.js     1 MB       1  [emitted]  [big]  lib
      vendor.min.js  1.07 kB       2  [emitted]         vendor
    manifest.min.js  5.88 kB       3  [emitted]         manifest
    main.min.js.map  2.42 MB       0  [emitted]         main
     lib.min.js.map  1.18 MB       1  [emitted]         lib
  vendor.min.js.map  1.31 kB       2  [emitted]         vendor
manifest.min.js.map  5.98 kB       3  [emitted]         manifest

ERROR in ./web/js/module-registry.js
Module not found: Error: Can't resolve 'pim/family-variant-edit-form/axes' in '/var/www/html/pim-community-standard/web/js'
 @ ./web/js/module-registry.js 2:68883-68935
 @ ./vendor/akeneo/pim-community-dev/webpack/require-context.js
 @ ./web/bundles/pimenrich/js/form/builder.js
 @ ./web/bundles/pimenrich/js/index.js
 @ multi babel-polyfill ./web/bundles/pimenrich/js/index.js

ERROR in ./web/js/module-registry.js
Module not found: Error: Can't resolve 'pim/form/common/creation/family' in '/var/www/html/pim-community-standard/web/js'
 @ ./web/js/module-registry.js 2:68970-69020
 @ ./vendor/akeneo/pim-community-dev/webpack/require-context.js
 @ ./web/bundles/pimenrich/js/form/builder.js
 @ ./web/bundles/pimenrich/js/index.js
 @ multi babel-polyfill ./web/bundles/pimenrich/js/index.js

ERROR in ./web/js/module-registry.js
Module not found: Error: Can't resolve 'pim/template/family-variant/axes' in '/var/www/html/pim-community-standard/web/js'
 @ ./web/js/module-registry.js 2:69145-69196
 @ ./vendor/akeneo/pim-community-dev/webpack/require-context.js
 @ ./web/bundles/pimenrich/js/form/builder.js
 @ ./web/bundles/pimenrich/js/index.js
 @ multi babel-polyfill ./web/bundles/pimenrich/js/index.js

ERROR in ./web/js/module-registry.js
Module not found: Error: Can't resolve 'pim/template/form/creation/family' in '/var/www/html/pim-community-standard/web/js'
 @ ./web/js/module-registry.js 2:69057-69109
 @ ./vendor/akeneo/pim-community-dev/webpack/require-context.js
 @ ./web/bundles/pimenrich/js/form/builder.js
 @ ./web/bundles/pimenrich/js/index.js
 @ multi babel-polyfill ./web/bundles/pimenrich/js/index.js
verbose 14.978 Error: Command failed.
Exit code: 2
Command: sh
Arguments: -c yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
Directory: /var/www/html/pim-community-standard
Output:

    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:186:110)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:226:113)
    at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:30281:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
Directory: /var/www/html/pim-community-standard
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/html/pim-community-standard/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by skeleton** [comment]
Hello, can you run `bin/pim-front.sh` command please?

**Comment by alekseyp** [comment]
I had different error, but `bin/pim-front.sh` fixed it. That step is not part of the docs btw.

```
docker-compose run --rm node yarn run webpack
yarn run v1.5.1
warning package.json: No license field
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod --env=dev
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
Starting webpack from /srv/pim in prod mode

WebpackCleanupPlugin: 0 file(s) deleted.
Version: webpack 3.5.5
Time: 5048ms
              Asset     Size  Chunks                    Chunk Names
        main.min.js   546 kB       0  [emitted]  [big]  main
      vendor.min.js  1.07 kB       1  [emitted]         vendor
    manifest.min.js  5.87 kB       2  [emitted]         manifest
    main.min.js.map   724 kB       0  [emitted]         main
  vendor.min.js.map  1.31 kB       1  [emitted]         vendor
manifest.min.js.map  5.97 kB       2  [emitted]         manifest

ERROR in ./web/bundles/pimenrich/js/index.js
Module not found: Error: Can't resolve 'pim/form-builder' in '/srv/pim/web/bundles/pimenrich/js'
 @ ./web/bundles/pimenrich/js/index.js 1:13-138
 @ multi babel-polyfill ./web/bundles/pimenrich/js/index.js
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod --env=dev
Directory: /srv/pim
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/srv/pim/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Doodoune** [comment]
Hi!

Do you still have this issue?
On the documentation, we explain that when you apply a patch or when you customize the frontend, you need to rebuild assets and clear the cache:
https://docs.akeneo.com/2.3/migrate_pim/index.html#how-to-apply-a-patch
https://docs.akeneo.com/2.3/design_pim/overview.html#make-it-available

Hope it will help you,
Regards,

**Comment by Doodoune** [comment]
I closing this issue.
Feel free to reopen if needed.

Regards,
