### ISSUE TITLE
yarn run webpack fails on missing dependency

### ISSUE THREAD

**Issue by stefandoorn** [akeneo/pim-community-dev#9557]
On Akeneo v3.0.1. It looks to me like there is a dependency used in the `webpack` command that is not included when installing production dependencies.

```
RUN yarn install --production
---> Running in 428329900d67
yarn install v1.13.0
warning package.json: No license field
warning pim-community-standard@2.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 29.73s.
Removing intermediate container 428329900d67
 ---> bc34f7e3a541
Step 14/25 : RUN yarn run webpack
 ---> Running in 6c9432435fa2
yarn run v1.13.0
warning package.json: No license field
$ yarn run sync && NODE_PATH=node_modules webpack --config $npm_package_config_source/webpack.config.js --env=prod
warning package.json: No license field
$ NODE_PATH=node_modules node $npm_package_config_check --source=$npm_package_config_source
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'dep-diff'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/srv/pim/vendor/akeneo/pim-community-dev/webpack/check-dependencies.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

**Comment by stefandoorn** [comment]
Related to https://github.com/akeneo/pim-community-standard/pull/460

**Comment by Doodoune** [comment]
Hi @stefandoorn!
I try on a fresh install of 3.0.11 and I don't reproduce this issue. 
I launch a `docker-compose run --rm node yarn install --production` and then launch a `docker-compose run --rm node yarn run webpack`. All is done without errors.
Regards,

**Comment by stefandoorn** [comment]
Ah, maybe it's fixed in the meanwhile! I've seen some PR's regarding yarn dependencies, but haven't looked into detail into them. Then for now we can close it I think.
